FROM python:3.10-slim

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar el archivo de Python a /app dentro del contenedor
COPY . /app

# Comando para ejecutar el script de Python
CMD ["python", "juego.py"]
